DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS TM_CURRENCIES;

CREATE TABLE ACCOUNTS(ID INT PRIMARY KEY,
   NAME VARCHAR(255) UNIQUE, 
   CURRENCY INT NOT NULL,
   BALANCE DOUBLE (99),
   TREASURY BOOLEAN not NULL
   );
   
CREATE TABLE TM_CURRENCIES (ID INT PRIMARY KEY, 
	CODE VARCHAR (3) UNIQUE NOT NULL, 
	NAME VARCHAR(100));

ALTER TABLE ACCOUNTS
    ADD FOREIGN KEY (CURRENCY) 
    REFERENCES TM_CURRENCIES(ID);

INSERT INTO TM_CURRENCIES (ID, CODE, NAME)
	VALUES (1, 'EUR', 'Euro');  
INSERT INTO TM_CURRENCIES (ID, CODE, NAME)
	VALUES (2, 'USD', 'US Dolar');
INSERT INTO TM_CURRENCIES (ID, CODE, NAME)
	VALUES (3, 'GBP', 'Pound sterling');  
INSERT INTO TM_CURRENCIES (ID, CODE, NAME)
	VALUES (4, 'INR', 'Indian rupee');
INSERT INTO TM_CURRENCIES (ID, CODE, NAME)
	VALUES (5, 'JPY', 'Japanese yen');  
	
INSERT INTO ACCOUNTS (ID, NAME, CURRENCY, BALANCE, TREASURY)
	VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'A', 1, 250, TRUE);

  INSERT INTO ACCOUNTS (ID, NAME, CURRENCY, BALANCE, TREASURY)
  	VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'B', 1, 1000, FALSE);

INSERT INTO ACCOUNTS (ID, NAME, CURRENCY, BALANCE, TREASURY)
	VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'C', 2, 500, FALSE);

  INSERT INTO ACCOUNTS (ID, NAME, CURRENCY, BALANCE, TREASURY)
  	VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'D', 2, 1500, FALSE);
	
	